version: '3.8'

services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./gateway:/app/src
      - /app/node_modules
    environment:
      USER_SERVICE_URL: http://user-service:3001
      EVENT_SERVICE_URL: http://event-service:3002
      NOTIFICATION_SERVICE_URL: http://notification-service:3003
    depends_on:
      - user-service
      - event-service
      - notification-service

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    volumes:
      - ./user-service/src:/app/src
      - /app/node_modules
    environment:
      NODE_ENV: development
      DATABASE_HOST: user-service-db
      DATABASE_PORT: 5432
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      DATABASE_NAME: usersdb
    depends_on:
      - user-service-db

  user-service-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: usersdb
    ports:
      - "5432:5432"
    volumes:
      - user-service-db:/var/lib/postgresql/data

  event-service:
    build:
      context: ./event-service
      dockerfile: Dockerfile.dev
    ports:
      - "3002:3002"
    volumes:
      - ./event-service/src:/app/src
      - /app/node_modules
    environment:
      NODE_ENV: development
      DATABASE_HOST: event-service-db
      DATABASE_PORT: 5432
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      DATABASE_NAME: eventsdb
    depends_on:
      - event-service-db

  event-service-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: eventsdb
    ports:
      - "5433:5432"
    volumes:
      - event-service-db:/var/lib/postgresql/data

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile.dev
    ports:
      - "3003:3003"
    volumes:
      - ./notification-service/src:/app/src
      - /app/node_modules
    env_file:
      - ./notification-service/.env
    depends_on:
      - notification-service-db

  notification-service-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notificationsdb
    ports:
      - "5434:5432"
    volumes:
      - notification-service-db:/var/lib/postgresql/data

  next-app:
    build: ./monui-frontend
    container_name: next-app
    ports:
      - "3005:3000" 
    environment:
      - NODE_ENV=production
      - API_URL=http://gateway:3000  
    depends_on:
      - gateway

volumes:
  user-service-db:
  event-service-db:
  notification-service-db:
