version: '3.8'

services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./gateway:/app/src
    env_file:
      - ./gateway/.env
    depends_on:
      - user-service
      - event-service
      - notification-service

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    volumes:
      - ./user-service/src:/app/src
    env_file:
      - ./user-service/.env
    depends_on:
      - user-service-db

  user-service-db:
    image: postgres:15
    restart: always
    env_file:
      - ./user-service/.env
    ports:
      - "5432:5432"
    volumes:
      - user-service-db:/var/lib/postgresql/data

  event-service:
    build:
      context: ./event-service
      dockerfile: Dockerfile.dev
    ports:
      - "3002:3002"
    volumes:
      - ./event-service/src:/app/src
    env_file:
      - ./event-service/.env
    depends_on:
      - event-service-db

  event-service-db:
    image: postgres:15
    restart: always
    env_file:
      - ./event-service/.env
    ports:
      - "5433:5432"
    volumes:
      - event-service-db:/var/lib/postgresql/data

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile.dev
    ports:
      - "3003:3003"
    volumes:
      - ./notification-service/src:/app/src
    env_file:
      - ./notification-service/.env
    depends_on:
      - notification-service-db

  notification-service-db:
    image: postgres:15
    restart: always
    env_file:
      - ./notification-service/.env
    ports:
      - "5434:5432"
    volumes:
      - notification-service-db:/var/lib/postgresql/data

  next-app:
    build:
      context: ./monui-frontend
      dockerfile: Dockerfile.dev
    container_name: next-app
    ports:
      - "3005:3000"
    volumes:
      - ./monui-frontend:/app
    env_file:
      - ./monui-frontend/.env
    depends_on:
      - gateway

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile.dev
    ports:
      - "3004:3004"
    volumes:
      - ./auth-service/src:/app/src
    env_file:
      - ./auth-service/.env
    depends_on:
      - user-service



volumes:
  user-service-db:
  event-service-db:
  notification-service-db:
